<?php

/**
 * This is the model base class for the table "categoria".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Categoria".
 *
 * Columns in table "categoria" available as properties of the model,
 * followed by relations of table "categoria" available as properties of the model.
 *
 * @property integer $categoria_id
 * @property string $nome
 * @property string $cadastrado
 * @property string $atualizado
 *
 * @property Post[] $posts
 */
abstract class BaseCategoria extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'categoria';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Categoria|Categorias', $n);
	}

	public static function representingColumn() {
		return 'nome';
	}

	public function rules() {
		return array(
			array('nome', 'length', 'max'=>255),
			array('cadastrado, atualizado', 'safe'),
			array('nome, cadastrado, atualizado', 'default', 'setOnEmpty' => true, 'value' => null),
			array('categoria_id, nome, cadastrado, atualizado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'posts' => array(self::HAS_MANY, 'Post', 'categoria_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'categoria_id' => Yii::t('app', 'Categoria'),
			'nome' => Yii::t('app', 'Nome'),
			'cadastrado' => Yii::t('app', 'Cadastrado'),
			'atualizado' => Yii::t('app', 'Atualizado'),
			'posts' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('categoria_id', $this->categoria_id);
		$criteria->compare('nome', $this->nome, true);
		$criteria->compare('cadastrado', $this->cadastrado, true);
		$criteria->compare('atualizado', $this->atualizado, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}