<?php

/**
 * This is the model base class for the table "post".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Post".
 *
 * Columns in table "post" available as properties of the model,
 * followed by relations of table "post" available as properties of the model.
 *
 * @property integer $post_id
 * @property string $titulo
 * @property string $texto
 * @property string $data
 * @property integer $visualizacoes
 * @property integer $categoria_id
 * @property integer $usuario_id
 * @property string $cadastrado
 * @property string $atualizado
 *
 * @property Comentario[] $comentarios
 * @property Categoria $categoria
 * @property Usuario $usuario
 */
abstract class BasePost extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'post';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Post|Posts', $n);
	}

	public static function representingColumn() {
		return 'titulo';
	}

	public function rules() {
		return array(
			array('titulo, texto, categoria_id', 'required'),
			array('visualizacoes, categoria_id, usuario_id', 'numerical', 'integerOnly'=>true),
			array('titulo', 'length', 'max'=>255),
			array('data, cadastrado, atualizado', 'safe'),
			array('titulo, data, visualizacoes, categoria_id, usuario_id, cadastrado, atualizado', 'default', 'setOnEmpty' => true, 'value' => null),
			array('post_id, titulo, texto, data, visualizacoes, categoria_id, usuario_id, cadastrado, atualizado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'comentarios' => array(self::HAS_MANY, 'Comentario', 'post_id', 'order'=>'comentarios.data DESC'),
			'categoria' => array(self::BELONGS_TO, 'Categoria', 'categoria_id'),
			'usuario' => array(self::BELONGS_TO, 'Usuario', 'usuario_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'post_id' => Yii::t('app', 'Post'),
			'titulo' => Yii::t('app', 'Título'),
			'texto' => Yii::t('app', 'Texto'),
			'data' => Yii::t('app', 'Data'),
			'visualizacoes' => Yii::t('app', 'Visualizações'),
			'categoria_id' => null,
			'usuario_id' => null,
			'cadastrado' => Yii::t('app', 'Cadastrado'),
			'atualizado' => Yii::t('app', 'Atualizado'),
			'comentarios' => null,
			'categoria' => null,
			'usuario' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('post_id', $this->post_id);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('texto', $this->texto, true);
		$criteria->compare('data', $this->data, true);
		$criteria->compare('visualizacoes', $this->visualizacoes);
		$criteria->compare('categoria_id', $this->categoria_id);
		$criteria->compare('usuario_id', $this->usuario_id);
		$criteria->compare('cadastrado', $this->cadastrado, true);
		$criteria->compare('atualizado', $this->atualizado, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}